[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "6b1a9aef90f4a1731747cbbf8f325c22346a2a71"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "08d219757d7621e81650d63d6c6c9087214c41ff5bbd4a813b3e67a0ab658bc0"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.aarch64-linux-gnu.tar.gz"
[[hidapi]]
arch = "aarch64"
git-tree-sha1 = "9915bd02b573b327d776ac7fe975c1503b426d11"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "41c0a33121b91b0cd1c17ec139f85311bc14588886d64b919f34171c8a09cbe2"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.aarch64-linux-musl.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "102ea68be30c1efcdf9a82ad549067390fb72c5c"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "91a1b9eb40a357a2d6b476e275eacb74f8861457166d772504bf54bf81a80289"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.armv7l-linux-gnueabihf.tar.gz"
[[hidapi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a61bf70c780dbe08c1220d2da0cff4695e38159"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "5c1d942d16e7f15d06b85fdeb3ac121cf91c060ed9f572ee989f44a95dd61b1b"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.armv7l-linux-musleabihf.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "1dd1960b0bbf64dd12e092d7d38395624880399d"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "cb36bc9f652609c19e5e9dec5f691b52327a1b4c7e0068159ae31725d407a3fe"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.i686-linux-gnu.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "4c1226fc28ad6248240a1e89b589e5293fbd4447"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "32e65e27ce2acffc0c4ccde7561d4df773b901ed19363cb678906f2f56af1a19"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.i686-linux-musl.tar.gz"
[[hidapi]]
arch = "i686"
git-tree-sha1 = "3dc21c7f8948cb3624a5bfe3e3303386be97024a"
os = "windows"

    [[hidapi.download]]
    sha256 = "95cf4778f05a3c67f36adc9b881bbf52cb93acb4c2f1c8efa2a0efeb42202fda"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.i686-w64-mingw32.tar.gz"
[[hidapi]]
arch = "powerpc64le"
git-tree-sha1 = "1829441346cb5bc623bd3be8f03b5a1a4ba882a5"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "3e19f481cc47eabeb90ca93906d2f748712b3ff9b3681fbe23c2b1c4e2d22211"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.powerpc64le-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "4f67c480d4664b897295212f8a2ac97f12679139"
os = "macos"

    [[hidapi.download]]
    sha256 = "154124f1fb79bd045e85ce6ccb2144a07c5998cc3c422218fd41068e5ab475d9"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.x86_64-apple-darwin.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "ed987a61c3d4fb544b11b3db7965711773b6c8a2"
libc = "glibc"
os = "linux"

    [[hidapi.download]]
    sha256 = "93359a06abca09c2ce79047d7618c91b687e2fadb53795852a948121090a4f3f"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.x86_64-linux-gnu.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "d4f4bccb2ce98c0e705139f1d2a2cd159376afc7"
libc = "musl"
os = "linux"

    [[hidapi.download]]
    sha256 = "b2e95d9c807a616b32aa2a72db2ccb6211fc65c8e3f463c9f7c53f85c0906520"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.x86_64-linux-musl.tar.gz"
[[hidapi]]
arch = "x86_64"
git-tree-sha1 = "5d73aa9bf8895184b14ced7896e9576144d82c67"
os = "windows"

    [[hidapi.download]]
    sha256 = "ec7b7b464a1328b293391d6afc6b279bbbc638c877439c5e0d3b398b790fd1bc"
    url = "https://github.com/laborg/hidapi_jll.jl/releases/download/hidapi-v0.10.0+0/hidapi.v0.10.0.x86_64-w64-mingw32.tar.gz"
