# Autogenerated wrapper script for hidapi_jll for x86_64-w64-mingw32
export hidapi

using libusb_jll
JLLWrappers.@generate_wrapper_header("hidapi")
JLLWrappers.@declare_library_product(hidapi, "libhidapi-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll)
    JLLWrappers.@init_library_product(
        hidapi,
        "bin\\libhidapi-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
