# Autogenerated wrapper script for hidapi_jll for x86_64-apple-darwin
export hidapi

using libusb_jll
JLLWrappers.@generate_wrapper_header("hidapi")
JLLWrappers.@declare_library_product(hidapi, "@rpath/libhidapi.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll)
    JLLWrappers.@init_library_product(
        hidapi,
        "lib/libhidapi.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
